### ISSUE TITLE
Localization needed

### ISSUE THREAD

**Issue by AlzioNever** [tnsogs02/notatsukinotanoshi#18]
Warning info
mail counter
Navbar translation

**Comment by Duct-and-rice** [comment]
translation_japanese looks like very busy now, so I post this without review by other Japanese.

My draft for Japanese:
500 error
> もしHTTP 500エラーが発生した場合、メールをコピーして普通にクライアント等で送るか、以下のQRコードを読み取って使ってみてください。
> また、Gmailを使っていない場合も、同様にしてください。
> ご不便をおかけしてごめんなさい。

navbar
> Participate -> メールを送る (Retranslation: "Send Mail")
> About -> このプロジェクトについて (Retranslation: "About this project")

**Comment by Duct-and-rice** [comment]
No. of mails sent:
> 送られたメールの数

**Comment by tnsogs02** [comment]
Finished
